cities = {
    # Europe
    "Amsterdam, Netherlands": "AMS",
    "Athens, Greece": "ATH",
    "Barcelona, Spain": "BCN",
    "Berlin, Germany": "BER",
    "Brussels, Belgium": "BRU",
    "Budapest, Hungary": "BUD",
    "Copenhagen, Denmark": "CPH",
    "Dublin, Ireland": "DUB",
    "Edinburgh, England, United Kingdom": "EDI",
    "Florence, Italy": "FLR",
    "Frankfurt, Germany": "FRA",
    "Geneva, Switzerland": "GVA",
    "Helsinki, Finland": "HEL",
    "Istanbul, Turkey": "IST",
    "Krakow, Poland": "KRK",
    "Lisbon, Portugal": "LIS",
    "London, England, United Kingdom": "LON",
    "Madrid, Spain": "MAD",
    "Manchester, England, United Kingdom": "MAN",
    "Milan, Italy": "MIL",
    "Moscow, Russia": "MOW",
    "Munich, Germany": "MUC",
    "Naples, Italy": "NAP",
    "Oslo, Norway": "OSL",
    "Paris, France": "PAR",
    "Prague, Czech Republic": "PRG",
    "Reykjavik, Iceland": "REK",
    "Rome, Italy": "ROM",
    "Saint Petersburg, Russia": "LED",
    "Stockholm, Sweden": "STO",
    "Vienna, Austria": "VIE",
    "Warsaw, Poland": "WAW",
    "Zagreb, Croatia": "ZAG",
    "Amalfi, Italy": "AML",
    "Antwerp, Belgium": "ANR",
    "Belfast, England, United Kingdom": "BFS",
    "Bergen, Norway": "BGO",
    "Bucharest, Romania": "BUH",
    "Cologne, Germany": "CGN",
    "Dresden, Germany": "DRS",
    "Glasgow, England, United Kingdom": "GLA",
    "Hamburg, Germany": "HAM",
    "Ljubljana, Slovenia": "LJU",
    "Luxembourg City, Luxembourg": "LUX",
    "Marseille, France": "MRS",
    "Oxford, England, United Kingdom": "OXF",
    "Rotterdam, Netherlands": "RTM",
    "Salzburg, Austria": "SZG",
    "Seville, Spain": "SVQ",
    "Valencia, Spain": "VLC",
    "Venice, Italy": "VCE",
    "Catania, Sicily ,Italy": "CTA",
    "Palermo, Sicily, Italy": "PMO",
    # Asia
    "Bangkok, Thailand": "BKK",
    "Beijing, China": "PEK",
    "Dubai, United Arab Emirates": "DXB",
    "Hong Kong, China": "HKG",
    "Istanbul, Turkey": "IST",
    "Jakarta, Indonesia": "JKT",
    "Kuala Lumpur, Malaysia": "KUL",
    "Kyoto, Japan": "UKY",
    "Manila, Philippines": "MNL",
    "Mumbai, India": "BOM",
    "New Delhi, India": "DEL",
    "Osaka, Japan": "OSA",
    "Phuket, Thailand": "HKT",
    "Seoul, South Korea": "SEL",
    "Shanghai, China": "PVG",
    "Singapore, Singapore": "SIN",
    "Sydney, Australia": "SYD",
    "Taipei, Taiwan": "TPE",
    "Tokyo, Japan": "TYO",
    "Abu Dhabi, United Arab Emirates": "AUH",
    "Almaty, Kazakhstan": "ALA",
    "Amman, Jordan": "AMM",
    "Astana, Kazakhstan": "TSE",
    "Baghdad, Iraq": "BGW",
    "Baku, Azerbaijan": "GYD",
    "Bandar Seri Begawan, Brunei": "BWN",
    "Colombo, Sri Lanka": "CMB",
    "Dhaka, Bangladesh": "DAC",
    "Dushanbe, Tajikistan": "DYU",
    "Hanoi, Vietnam": "HAN",
    "Islamabad, Pakistan": "ISB",
    "Eilat, Israel": "ETM",
    "Kabul, Afghanistan": "KBL",
    "Kathmandu, Nepal": "KTM",
    "Kolkata, India": "CCU",
    "Kuwait City, Kuwait": "KWI",
    "Male, Maldives": "MLE",
    "Muscat, Oman": "MCT",
    "Nur-Sultan, Kazakhstan": "NQZ",
    "Pyongyang, North Korea": "FNJ",
    "Riyadh, Saudi Arabia": "RUH",
    "Tashkent, Uzbekistan": "TAS",
    "Tel Aviv, Israel": "TLV",
    "Thimphu, Bhutan": "PBH",
    "Ulaanbaatar, Mongolia": "ULN",
    "Vientiane, Laos": "VTE",
    "Yangon, Myanmar": "RGN",
    "Yerevan, Armenia": "EVN",
    # North America
    "Atlanta, Georgia, United States": "ATL",
    "Boston, Massachusetts, United States": "BOS",
    "Calgary, Canada": "YYC",
    "Chicago, Illinois, United States": "CHI",
    "Dallas, Texas, United States": "DFW",
    "Denver, Colorado, United States": "DEN",
    "Detroit, Michigan, United States": "DTW",
    "Edmonton, Canada": "YEG",
    "Guadalajara, Mexico": "GDL",
    "Halifax, Canada": "YHZ",
    "Havana, Cuba": "HAV",
    "Houston, Texas, United States": "HOU",
    "Las Vegas, Nevada, United States": "LAS",
    "Los Angeles, California, United States": "LAX",
    "Mexico City, Mexico": "MEX",
    "Miami, Florida, United States": "MIA",
    "Montreal, Canada": "YUL",
    "Nashville, Tennessee, United States": "BNA",
    "New Orleans, Louisiana, United States": "MSY",
    "New York City, New York, United States": "NYC",
    "Ottawa, Canada": "YOW",
    "Philadelphia, Pennsylvania, United States": "PHL",
    "Phoenix, Arizona, United States": "PHX",
    "Portland, Oregon, United States": "PDX",
    "Quebec City, Canada": "YQB",
    "San Diego, California, United States": "SAN",
    "San Francisco, California, United States": "SFO",
    "San Jose, California, United States": "SJC",
    "Santa Fe, New Mexico, United States": "SAF",
    "Seattle, Washington, United States": "SEA",
    "Toronto, Canada": "YYZ",
    "Vancouver, Canada": "YVR",
    "Washington D.C., United States": "WAS",
    "Anchorage, Alaska, United States": "ANC",
    "Aspen, Colorado, United States": "ASE",
    "Cancun, Mexico": "CUN",
    "Charleston, South Carolina, United States": "CHS",
    "Honolulu, Hawaii, United States": "HNL",
    "Jackson, Wyoming, United States": "JAC",
    "Kahului, Hawaii, United States": "OGG",
    "Kingston, Jamaica": "KIN",
    "Mazatlan, Mexico": "MZT",
    "Monterrey, Mexico": "MTY",
    "Nassau, Bahamas": "NAS",
    "Puerto Vallarta, Mexico": "PVR",
    "San Juan, Puerto Rico": "SJU",
    "Santo Domingo, Dominican Republic": "SDQ",
    "St. John\'s, Canada": "YYT",
    "Tijuana, Mexico": "TIJ",
    # South America
    "Belo Horizonte, Brazil": "BHZ",
    "Bogotá, Colombia": "BOG",
    "Buenos Aires, Argentina": "BUE",
    "Caracas, Venezuela": "CCS",
    "Córdoba, Argentina": "COR",
    "Curitiba, Brazil": "CWB",
    "Fortaleza, Brazil": "FOR",
    "Guayaquil, Ecuador": "GYE",
    "La Paz, Bolivia": "LPB",
    "Lima, Peru": "LIM",
    "Manaus, Brazil": "MAO",
    "Medellín, Colombia": "MDE",
    "Montevideo, Uruguay": "MVD",
    "Porto Alegre, Brazil": "POA",
    "Port-au-Prince, Haiti": "PAP",
    "Quito, Ecuador": "UIO",
    "Recife, Brazil": "REC",
    "Rio de Janeiro, Brazil": "RIO",
    "Salvador, Brazil": "SSA",
    "Santiago, Chile": "SCL",
    "Santo Domingo, Dominican Republic": "SDQ",
    "São Paulo, Brazil": "SAO",
    "Asunción, Paraguay": "ASU",
    "Brasília, Brazil": "BSB",
    "Cali, Colombia": "CLO",
    "Campos do Jordão, Brazil": "CPJ",
    "Cartagena, Colombia": "CTG",
    "Cusco, Peru": "CUZ",
    "Foz do Iguaçu, Brazil": "IGU",
    "Goiania, Brazil": "GYN",
    "Jujuy, Argentina": "JUJ",
    "Mendoza, Argentina": "MDZ",
    "Natal, Brazil": "NAT",
    "Pucón, Chile": "ZPC",
    "Puerto Iguazú, Argentina": "IGR",
    "Punta Arenas, Chile": "PUQ",
    "Punta del Este, Uruguay": "PDP",
    "Santa Cruz de la Sierra, Bolivia": "VVI",
    "São Luís, Brazil": "SLZ",
    "Teresina, Brazil": "THE",
    "Ushuaia, Argentina": "USH",
    "Valdivia, Chile": "ZAL",
    "Valparaíso, Chile": "VAP",
    "Vitoria, Brazil": "VIX",
    "Volcán Arenal, Costa Rica": "FON",
    "Zapallar, Chile": "ZPC",
    # Africa
    "Abidjan, Ivory Coast": "ABJ",
    "Accra, Ghana": "ACC",
    "Addis Ababa, Ethiopia": "ADD",
    "Algiers, Algeria": "ALG",
    "Asmara, Eritrea": "ASM",
    "Bamako, Mali": "BKO",
    "Cairo, Egypt": "CAI",
    "Cape Town, South Africa": "CPT",
    "Casablanca, Morocco": "CAS",
    "Conakry, Guinea": "CKY",
    "Dakar, Senegal": "DKR",
    "Dar es Salaam, Tanzania": "DAR",
    "Djibouti City, Djibouti": "JIB",
    "Douala, Cameroon": "DLA",
    "Durban, South Africa": "DUR",
    "Entebbe, Uganda": "EBB",
    "Harare, Zimbabwe": "HRE",
    "Johannesburg, South Africa": "JNB",
    "Kampala, Uganda": "KLA",
    "Kano, Nigeria": "KAN",
    "Khartoum, Sudan": "KRT",
    "Kinshasa, Congo": "FIH",
    "Lagos, Nigeria": "LOS",
    "Libreville, Gabon": "LBV",
    "Lilongwe, Malawi": "LLW",
    "Luanda, Angola": "LAD",
    "Lusaka, Zambia": "LUN",
    "Marrakesh, Morocco": "RAK",
    "Mogadishu, Somalia": "MGQ",
    "Nairobi, Kenya": "NBO",
    "Ndjamena, Chad": "NDJ",
    "Ouagadougou, Burkina Faso": "OUA",
    "Port Elizabeth, South Africa": "PLZ",
    "Port Harcourt, Nigeria": "PHC",
    "Pretoria, South Africa": "PRY",
    "Rabat, Morocco": "RBA",
    "Tunis, Tunisia": "TUN",
    "Victoria Falls, Zimbabwe": "VFA",
    "Windhoek, Namibia": "WDH",
    "Yaoundé, Cameroon": "NSI",
    "Zanzibar City, Tanzania": "ZNZ",
    # Oceania
    "Adelaide, Australia": "ADL",
    "Auckland, New Zealand": "AKL",
    "Brisbane, Australia": "BNE",
    "Cairns, Australia": "CNS",
    "Canberra, Australia": "CBR",
    "Christchurch, New Zealand": "CHC",
    "Darwin, Australia": "DRW",
    "Dunedin, New Zealand": "DUD",
    "Gold Coast, Australia": "OOL",
    "Hobart, Australia": "HBA",
    "Honolulu, Hawaii, United States": "HNL",
    "Melbourne, Australia": "MEL",
    "Nadi, Fiji": "NAN",
    "Noumea, New Caledonia": "NOU",
    "Pago Pago, American Samoa": "PPG",
    "Perth, Australia": "PER",
    "Port Moresby, Papua New Guinea": "POM",
    "Port Vila, Vanuatu": "VLI",
    "Queenstown, New Zealand": "ZQN",
    "Rarotonga, Cook Islands": "RAR",
    "Sydney, Australia": "SYD",
    "Tahiti, French Polynesia": "PPT",
    "Tauranga, New Zealand": "TRG",
    "Townsville, Australia": "TSV",
    "Wellington, New Zealand": "WLG",
    "Apia, Samoa": "APW",
    "Avarua, Cook Islands": "AIT",
    "Bora Bora, French Polynesia": "BOB",
    "Broome, Australia": "BME",
    "Coffs Harbour, Australia": "CFS",
    "Dili, Timor-Leste": "DIL",
    "Fiji, Fiji": "SUV",
    "Gisborne, New Zealand": "GIS",
    "Hamilton Island, Australia": "HTI",
    "Hervey Bay, Australia": "HVB",
    "Kiritimati, Kiribati": "CXI",
    "Koror, Palau": "ROR",
    "Lihue, Hawaii, United States": "LIH",
    "Majuro, Marshall Islands": "MAJ",
    "Nouméa, New Caledonia": "GEA",
    "Nuku alofa, Tonga": "TBU",
    "Papeete, French Polynesia": "PPT",
    "Rabaul, Papua New Guinea": "RAB",
    "Rockhampton, Australia": "ROK",
    "Rotorua, New Zealand": "ROT",
    "Suva, Fiji": "SUV",
    "Tonga, Tonga": "TBU",
    "Vanuatu, Vanuatu": "VLI"
}

cities_list = ['Amsterdam, Netherlands', 'Athens, Greece', 'Barcelona, Spain', 'Berlin, Germany', 'Brussels, Belgium',
               'Budapest, Hungary', 'Copenhagen, Denmark', 'Dublin, Ireland', 'Edinburgh, England, United Kingdom',
               'Florence, Italy', 'Frankfurt, Germany', 'Geneva, Switzerland', 'Helsinki, Finland', 'Istanbul, Turkey',
               'Krakow, Poland', 'Lisbon, Portugal', 'London, England, United Kingdom', 'Madrid, Spain',
               'Manchester, England, United Kingdom', 'Milan, Italy', 'Moscow, Russia', 'Munich, Germany',
               'Naples, Italy', 'Oslo, Norway', 'Paris, France', 'Prague, Czech Republic', 'Reykjavik, Iceland',
               'Rome, Italy', 'Saint Petersburg, Russia', 'Stockholm, Sweden', 'Vienna, Austria', 'Warsaw, Poland',
               'Zagreb, Croatia', 'Amalfi, Italy', 'Antwerp, Belgium', 'Belfast, England, United Kingdom',
               'Bergen, Norway', 'Bucharest, Romania', 'Cologne, Germany', 'Dresden, Germany',
               'Glasgow, England, United Kingdom', 'Hamburg, Germany', 'Ljubljana, Slovenia',
               'Luxembourg City, Luxembourg', 'Marseille, France', 'Oxford, England, United Kingdom',
               'Rotterdam, Netherlands', 'Salzburg, Austria', 'Seville, Spain', 'Valencia, Spain', 'Venice, Italy',
               'Catania, Sicily ,Italy', 'Palermo, Sicily, Italy', 'Bangkok, Thailand', 'Beijing, China',
               'Dubai, United Arab Emirates', 'Hong Kong, China', 'Jakarta, Indonesia', 'Kuala Lumpur, Malaysia',
               'Kyoto, Japan', 'Manila, Philippines', 'Mumbai, India', 'New Delhi, India', 'Osaka, Japan',
               'Phuket, Thailand', 'Seoul, South Korea', 'Shanghai, China', 'Singapore, Singapore', 'Sydney, Australia',
               'Taipei, Taiwan', 'Tokyo, Japan', 'Abu Dhabi, United Arab Emirates', 'Almaty, Kazakhstan',
               'Amman, Jordan', 'Astana, Kazakhstan', 'Baghdad, Iraq', 'Baku, Azerbaijan',
               'Bandar Seri Begawan, Brunei', 'Colombo, Sri Lanka', 'Dhaka, Bangladesh', 'Dushanbe, Tajikistan',
               'Hanoi, Vietnam', 'Islamabad, Pakistan', 'Eilat, Israel', 'Kabul, Afghanistan', 'Kathmandu, Nepal',
               'Kolkata, India', 'Kuwait City, Kuwait', 'Male, Maldives', 'Muscat, Oman', 'Nur-Sultan, Kazakhstan',
               'Pyongyang, North Korea', 'Riyadh, Saudi Arabia', 'Tashkent, Uzbekistan', 'Tel Aviv, Israel',
               'Thimphu, Bhutan', 'Ulaanbaatar, Mongolia', 'Vientiane, Laos', 'Yangon, Myanmar', 'Yerevan, Armenia',
               'Atlanta, Georgia, United States', 'Boston, Massachusetts, United States', 'Calgary, Canada',
               'Chicago, Illinois, United States', 'Dallas, Texas, United States', 'Denver, Colorado, United States',
               'Detroit, Michigan, United States', 'Edmonton, Canada', 'Guadalajara, Mexico', 'Halifax, Canada',
               'Havana, Cuba', 'Houston, Texas, United States', 'Las Vegas, Nevada, United States',
               'Los Angeles, California, United States', 'Mexico City, Mexico', 'Miami, Florida, United States',
               'Montreal, Canada', 'Nashville, Tennessee, United States', 'New Orleans, Louisiana, United States',
               'New York City, New York, United States', 'Ottawa, Canada', 'Philadelphia, Pennsylvania, United States',
               'Phoenix, Arizona, United States', 'Portland, Oregon, United States', 'Quebec City, Canada',
               'San Diego, California, United States', 'San Francisco, California, United States',
               'San Jose, California, United States', 'Santa Fe, New Mexico, United States',
               'Seattle, Washington, United States', 'Toronto, Canada', 'Vancouver, Canada',
               'Washington D.C., United States', 'Anchorage, Alaska, United States', 'Aspen, Colorado, United States',
               'Cancun, Mexico', 'Charleston, South Carolina, United States', 'Honolulu, Hawaii, United States',
               'Jackson, Wyoming, United States', 'Kahului, Hawaii, United States', 'Kingston, Jamaica',
               'Mazatlan, Mexico', 'Monterrey, Mexico', 'Nassau, Bahamas', 'Puerto Vallarta, Mexico',
               'San Juan, Puerto Rico', 'Santo Domingo, Dominican Republic', "St. John's, Canada", 'Tijuana, Mexico',
               'Belo Horizonte, Brazil', 'Bogotá, Colombia', 'Buenos Aires, Argentina', 'Caracas, Venezuela',
               'Córdoba, Argentina', 'Curitiba, Brazil', 'Fortaleza, Brazil', 'Guayaquil, Ecuador', 'La Paz, Bolivia',
               'Lima, Peru', 'Manaus, Brazil', 'Medellín, Colombia', 'Montevideo, Uruguay', 'Porto Alegre, Brazil',
               'Port-au-Prince, Haiti', 'Quito, Ecuador', 'Recife, Brazil', 'Rio de Janeiro, Brazil',
               'Salvador, Brazil', 'Santiago, Chile', 'São Paulo, Brazil', 'Asunción, Paraguay', 'Brasília, Brazil',
               'Cali, Colombia', 'Campos do Jordão, Brazil', 'Cartagena, Colombia', 'Cusco, Peru',
               'Foz do Iguaçu, Brazil', 'Goiania, Brazil', 'Jujuy, Argentina', 'Mendoza, Argentina', 'Natal, Brazil',
               'Pucón, Chile', 'Puerto Iguazú, Argentina', 'Punta Arenas, Chile', 'Punta del Este, Uruguay',
               'Santa Cruz de la Sierra, Bolivia', 'São Luís, Brazil', 'Teresina, Brazil', 'Ushuaia, Argentina',
               'Valdivia, Chile', 'Valparaíso, Chile', 'Vitoria, Brazil', 'Volcán Arenal, Costa Rica',
               'Zapallar, Chile', 'Abidjan, Ivory Coast', 'Accra, Ghana', 'Addis Ababa, Ethiopia', 'Algiers, Algeria',
               'Asmara, Eritrea', 'Bamako, Mali', 'Cairo, Egypt', 'Cape Town, South Africa', 'Casablanca, Morocco',
               'Conakry, Guinea', 'Dakar, Senegal', 'Dar es Salaam, Tanzania', 'Djibouti City, Djibouti',
               'Douala, Cameroon', 'Durban, South Africa', 'Entebbe, Uganda', 'Harare, Zimbabwe',
               'Johannesburg, South Africa', 'Kampala, Uganda', 'Kano, Nigeria', 'Khartoum, Sudan', 'Kinshasa, Congo',
               'Lagos, Nigeria', 'Libreville, Gabon', 'Lilongwe, Malawi', 'Luanda, Angola', 'Lusaka, Zambia',
               'Marrakesh, Morocco', 'Mogadishu, Somalia', 'Nairobi, Kenya', 'Ndjamena, Chad',
               'Ouagadougou, Burkina Faso', 'Port Elizabeth, South Africa', 'Port Harcourt, Nigeria',
               'Pretoria, South Africa', 'Rabat, Morocco', 'Tunis, Tunisia', 'Victoria Falls, Zimbabwe',
               'Windhoek, Namibia', 'Yaoundé, Cameroon', 'Zanzibar City, Tanzania', 'Adelaide, Australia',
               'Auckland, New Zealand', 'Brisbane, Australia', 'Cairns, Australia', 'Canberra, Australia',
               'Christchurch, New Zealand', 'Darwin, Australia', 'Dunedin, New Zealand', 'Gold Coast, Australia',
               'Hobart, Australia', 'Melbourne, Australia', 'Nadi, Fiji', 'Noumea, New Caledonia',
               'Pago Pago, American Samoa', 'Perth, Australia', 'Port Moresby, Papua New Guinea', 'Port Vila, Vanuatu',
               'Queenstown, New Zealand', 'Rarotonga, Cook Islands', 'Tahiti, French Polynesia',
               'Tauranga, New Zealand', 'Townsville, Australia', 'Wellington, New Zealand', 'Apia, Samoa',
               'Avarua, Cook Islands', 'Bora Bora, French Polynesia', 'Broome, Australia', 'Coffs Harbour, Australia',
               'Dili, Timor-Leste', 'Fiji, Fiji', 'Gisborne, New Zealand', 'Hamilton Island, Australia',
               'Hervey Bay, Australia', 'Kiritimati, Kiribati', 'Koror, Palau', 'Lihue, Hawaii, United States',
               'Majuro, Marshall Islands', 'Nouméa, New Caledonia', 'Nuku alofa, Tonga', 'Papeete, French Polynesia',
               'Rabaul, Papua New Guinea', 'Rockhampton, Australia', 'Rotorua, New Zealand', 'Suva, Fiji',
               'Tonga, Tonga', 'Vanuatu, Vanuatu']

attr_cities = ['Amsterdam',
               'Antwerp',
               'Athens',
               'Barcelona',
               'Berlin',
               'Boston',
               'Budapest',
               'Chicago',
               'Cologne',
               'Dresden',
               'Florence',
               'Frankfurt',
               'Hong Kong',
               'Lisbon',
               'London',
               'Madrid',
               'Milan',
               'Montreal',
               'Munich',
               'New Orleans',
               'New York',
               'Paris',
               'Philadelphia',
               'Prague',
               'Rome',
               'San Francisco',
               'Seville',
               'St Petersburg',
               'Stockholm',
               'Sydney',
               'Toronto',
               'Vancouver',
               'Venice',
               'Vienna',
               'Washington D.C.']
